# render.yaml
services:
  - type: web
    name: B2A2-Car-Auction
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --noinput
    startCommand: python manage.py runserver 0.0.0.0:8000
    autoDeploy: true
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: car_auction.settings
      - key: SECRET_KEY
        value: your-secret-key
      - key: DEBUG
        value: "False"
